/* Additional record code for TwoConnectedTanks generated by the OpenModelica Compiler OpenModelica v1.24.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "TwoConnectedTanks_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

